# Generated by Django 5.2.17 on 2026-09-28 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChecklistSeguranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_isolada",
                    models.BooleanField(
                        default=False, verbose_name="área isolada/sinalizada"
                    ),
                ),
                (
                    "confirmado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "checklist de segurança",
                "verbose_name_plural": "checklists de segurança",
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("CLASSIFICADO", "Aguardando atribuição"),
                            ("ATRIBUIDO", "Atribuído"),
                            ("EM_EXECUCAO", "Em execução"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        max_length=15,
                        verbose_name="status anterior",
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("CLASSIFICADO", "Aguardando atribuição"),
                            ("ATRIBUIDO", "Atribuído"),
                            ("EM_EXECUCAO", "Em execução"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        max_length=15,
                        verbose_name="status novo",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="data e hora"),
                ),
            ],
            options={
                "verbose_name": "histórico de status",
                "verbose_name_plural": "históricos de status",
                "ordering": ["data_hora"],
            },
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="descrição")),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("CLASSIFICADO", "Aguardando atribuição"),
                            ("ATRIBUIDO", "Atribuído"),
                            ("EM_EXECUCAO", "Em execução"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ABERTO",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "riscos",
                    models.TextField(blank=True, verbose_name="riscos identificados"),
                ),
                (
                    "aberta_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="aberta em"),
                ),
                (
                    "iniciada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="iniciada em"
                    ),
                ),
                (
                    "concluida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="concluída em"
                    ),
                ),
                (
                    "avaliacao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nota de 1 a 5.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="avaliação",
                    ),
                ),
                (
                    "justificativa_cancelamento",
                    models.TextField(
                        blank=True, verbose_name="justificativa do cancelamento"
                    ),
                ),
                (
                    "requer_revisao_seguranca",
                    models.BooleanField(
                        default=False, verbose_name="requer revisão de segurança"
                    ),
                ),
            ],
            options={
                "verbose_name": "ordem de serviço",
                "verbose_name_plural": "ordens de serviço",
                "ordering": ["-aberta_em"],
            },
        ),
        migrations.CreateModel(
            name="Preventiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodicidade_dias",
                    models.PositiveIntegerField(verbose_name="periodicidade (dias)"),
                ),
                ("proxima_data", models.DateField(verbose_name="próxima data")),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "preventiva",
                "verbose_name_plural": "preventivas",
                "ordering": ["proxima_data"],
            },
        ),
    ]
