# Generated by Django 5.2.17 on 2026-09-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estrutura", "0002_local_equipamento_local_local_unico_por_unidade"),
        ("ordens", "0001_initial"),
        ("seguranca", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistseguranca",
            name="epis_confirmados",
            field=models.ManyToManyField(
                blank=True,
                related_name="checklists",
                to="seguranca.epi",
                verbose_name="EPIs confirmados",
            ),
        ),
        migrations.AddField(
            model_name="historicostatus",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mudancas_status",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuário",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens",
                to="estrutura.equipamento",
                verbose_name="equipamento",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens",
                to="estrutura.local",
                verbose_name="local",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens_solicitadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="solicitante",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="tecnico",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"perfil": "TECNICO"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens_atribuidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="técnico",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="tipo_servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens",
                to="seguranca.tiposervico",
                verbose_name="tipo de serviço",
            ),
        ),
        migrations.AddField(
            model_name="historicostatus",
            name="ordem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico",
                to="ordens.ordemservico",
                verbose_name="ordem de serviço",
            ),
        ),
        migrations.AddField(
            model_name="checklistseguranca",
            name="ordem",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist",
                to="ordens.ordemservico",
                verbose_name="ordem de serviço",
            ),
        ),
        migrations.AddField(
            model_name="preventiva",
            name="equipamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preventivas",
                to="estrutura.equipamento",
                verbose_name="equipamento",
            ),
        ),
        migrations.AddField(
            model_name="preventiva",
            name="tipo_servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preventivas",
                to="seguranca.tiposervico",
                verbose_name="tipo de serviço",
            ),
        ),
    ]
