# Generated by Django 5.2.17 on 2026-09-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = (
        ("ordens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    )

    operations: list = [
        migrations.CreateModel(
            name="EPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "numero_ca",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="nº do CA"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
            ],
            options={
                "verbose_name": "EPI",
                "verbose_name_plural": "EPIs",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Treinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="código"),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "validade_meses",
                    models.PositiveSmallIntegerField(verbose_name="validade (meses)"),
                ),
            ],
            options={
                "verbose_name": "treinamento",
                "verbose_name_plural": "treinamentos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Incidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="descrição")),
                (
                    "gravidade",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("MODERADA", "Moderada"),
                            ("GRAVE", "Grave"),
                        ],
                        max_length=10,
                        verbose_name="gravidade",
                    ),
                ),
                (
                    "houve_lesao",
                    models.BooleanField(default=False, verbose_name="houve lesão"),
                ),
                (
                    "houve_afastamento",
                    models.BooleanField(
                        default=False, verbose_name="houve afastamento"
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="data e hora"),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidentes",
                        to="ordens.ordemservico",
                        verbose_name="ordem de serviço",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidentes_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "incidente",
                "verbose_name_plural": "incidentes",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="TipoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "eletrico",
                    models.BooleanField(
                        default=False,
                        help_text="Exige NR-10.",
                        verbose_name="serviço elétrico",
                    ),
                ),
                (
                    "trabalho_em_altura",
                    models.BooleanField(
                        default=False,
                        help_text="Exige NR-35.",
                        verbose_name="trabalho acima de 2 m",
                    ),
                ),
                (
                    "epis_exigidos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tipos_servico",
                        to="seguranca.epi",
                        verbose_name="EPIs exigidos",
                    ),
                ),
                (
                    "treinamentos_exigidos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tipos_servico",
                        to="seguranca.treinamento",
                        verbose_name="treinamentos exigidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de serviço",
                "verbose_name_plural": "tipos de serviço",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TreinamentoTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_realizacao",
                    models.DateField(verbose_name="data de realização"),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True,
                        help_text="Se vazio, é calculada pela validade do treinamento.",
                        verbose_name="data de validade",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        limit_choices_to={"perfil": "TECNICO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treinamentos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="técnico",
                    ),
                ),
                (
                    "treinamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realizacoes",
                        to="seguranca.treinamento",
                        verbose_name="treinamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "treinamento do técnico",
                "verbose_name_plural": "treinamentos dos técnicos",
                "ordering": ["-data_validade"],
            },
        ),
    ]
