# Generated by Django 5.2.17 on 2026-09-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "unidade",
                "verbose_name_plural": "unidades",
                "ordering": ["nome"],
            },
        ),
    ]
