# Generated by Django 5.2.17 on 2026-09-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estrutura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bloco", models.CharField(max_length=50, verbose_name="bloco")),
                ("andar", models.CharField(max_length=30, verbose_name="andar")),
                ("sala", models.CharField(max_length=50, verbose_name="sala")),
                (
                    "tipo_ambiente",
                    models.CharField(
                        choices=[
                            ("SALA_AULA", "Sala de aula"),
                            ("LABORATORIO", "Laboratório"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("AUDITORIO", "Auditório"),
                            ("COZINHA", "Cozinha"),
                            ("BANHEIRO", "Banheiro"),
                            ("AREA_EXTERNA", "Área externa"),
                            ("TECNICO", "Área técnica"),
                            ("OUTRO", "Outro"),
                        ],
                        default="SALA_AULA",
                        max_length=20,
                        verbose_name="tipo de ambiente",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locais",
                        to="estrutura.unidade",
                        verbose_name="unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "local",
                "verbose_name_plural": "locais",
                "ordering": ["unidade__nome", "bloco", "andar", "sala"],
            },
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "patrimonio",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="nº de patrimônio"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipamentos",
                        to="estrutura.local",
                        verbose_name="local",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipamento",
                "verbose_name_plural": "equipamentos",
                "ordering": ["nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="local",
            constraint=models.UniqueConstraint(
                fields=("unidade", "bloco", "andar", "sala"),
                name="local_unico_por_unidade",
            ),
        ),
    ]
